# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: bbdca8e54ce2ec4c66cf7ff708f710224275de06dd903d70e5a8d7692aa9ea8c67785e0fc1419f26f2751b7a8d0794bd0e9df893b5d4cdcc260ae14732f0b36d

test:
  secret_key_base: 29962b690f9af10ed6ea5df6789a106374bbf67db60171e423c22e16f8a4f19fed487e1daac4e47f49d5a692abb6739eb69e69ede361cee38e39c14f56ccaa74

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
